USE [master]
GO

/****** Object:  Database [BookStoreCatalog]    Script Date: 25.7.2013 г. 11:25:43 ******/
CREATE DATABASE [BookStoreCatalog]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookStoreCatalog', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\BookStoreCatalog.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BookStoreCatalog_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\BookStoreCatalog_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BookStoreCatalog] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookStoreCatalog].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BookStoreCatalog] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET ARITHABORT OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [BookStoreCatalog] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BookStoreCatalog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BookStoreCatalog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BookStoreCatalog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BookStoreCatalog] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET RECOVERY FULL 
GO

ALTER DATABASE [BookStoreCatalog] SET  MULTI_USER 
GO

ALTER DATABASE [BookStoreCatalog] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BookStoreCatalog] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BookStoreCatalog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BookStoreCatalog] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BookStoreCatalog] SET  READ_WRITE 
GO

